version: '3.3'

services:
  db:
    image: library/mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassRoot
      MYSQL_ROOT_PASSWORD: dbPassRoot
    ports:
    - '3306:3306'
    volumes:
    - "./.mysql-data/db:/var/lib/mysql"
